import localFont from "next/font/local";
import "./globals.css";
import Header from "./_components/Header/Header";
import Footer from "./_components/Footer/Footer";
import Com_Logos from "./_components/Com_Logos/Com_Logos";
import Top_Categories from "./_components/Top_Categories/Top_Categories";
import Topics_Categories from "./_components/Topics_Categories/Topics_Categories";
import Become_Instractor from "./_components/Become_Instractor/Become_Instractor";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return ( <
        html lang = "en" >
        <
        body className = { `${geistSans.variable} ${geistMono.variable} antialiased` } >
        <
        Header > < /Header> {children} <Com_Logos></Com_Logos >
        <
        Top_Categories > < /Top_Categories>{" "} <
        Topics_Categories > < /Topics_Categories>  <Become_Instractor></Become_Instractor > < Footer > < /Footer>{" "} <
        /body>{" "} <
        /html>
    );
}